name: CI/CD Pipeline for web-app

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

env:
  IMAGE_TAG: smabramovvv/my-app
  RELEASE_NAME: myapp
  NAMESPACE: my-app

jobs:
  build-and-push:
    name: Build Docker image
    runs-on: self-hosted  # Используем self-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version from tag or commit message
        run: |
          echo "GITHUB_REF: ${GITHUB_REF}"
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION=$(git log -1 --pretty=format:%B | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' || echo "latest")
          fi
          VERSION=${VERSION//[[:space:]]/}  # Remove any spaces
          echo "Using version: $VERSION"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_TAG }}:${{ env.VERSION }}

  deploy:
    needs: build-and-push
    name: Deploy to Kubernetes
    runs-on: self-hosted  # Используем self-hosted runner
    if: startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files in the working directory
        run: |
          ls -la

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.21.0'

      - name: Extract version from tag or commit message
        run: |
          echo "GITHUB_REF: ${GITHUB_REF}"
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION=$(git log -1 --pretty=format:%B | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' || echo "latest")
          fi
          VERSION=${VERSION//[[:space:]]/}  # Remove any spaces
          echo "Using version: $VERSION"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Replace image tag in app-deployment.yml
        run: |
          if [ ! -f ./deploy/app-deployment.yml ]; then
            echo "app-deployment.yml not found in the current directory"
            ls -la ./deploy/
            exit 1
          fi
          sed -i "s|image: smabramovvv/my-app:.*|image: ${{ env.IMAGE_TAG }}:${{ env.VERSION }}|" ./deploy/app-deployment.yml

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f ./deploy/app-deployment.yml
          kubectl get Deployment -n my-app
          kubectl get pods -n my-app
          if kubectl get Deployment myapp -n my-app; then
            kubectl describe Deployment myapp -n my-app
          else
            echo "Deployment myapp not found"
          fi
          if kubectl get service myapp-service -n my-app; then
            kubectl describe service myapp-service -n my-app
          else
            echo "Service myapp-service not found"
          fi
